### ISSUE TITLE
Trying to use mongo export result

### ISSUE THREAD

**Issue by kleber-swf** [benne/gulp-mongodb-data#5]
Hi there!
I'm using this project a while and I must say it's awesome. I never used to store the ObjectIds though. That's why I'm here.

Here it is my data: 

    [
        {
            "_id": "596a232dd7a9e34434c4df4c",
            "name": "foo"
            "category": {
                "$oid": "596a20587cc4ad065cd2cba1"
            }
        },
        {
            "_id": "596a232dd7a9e34434c4df4d",
            "name": "bar",
            "category": {
                "$oid": "596a20587cc4ad065cd2cba1"
            }
        },
        ...
    ]

This is the json I get when using the command:

    mongoexport -d <database> -c <collection> -o <file>.json --jsonArray

`_id ` works like expected, but `category` doesn't. Even `_id` dont't work if it has the `$oid` part. All of them throws this error:

    Error: key $oid must not start with '$'
        at serializeInto (...\node_modules\bson\lib\bson\parser\serializer.js:751:19)
        at serializeObject (...\node_modules\bson\lib\bson\parser\serializer.js:308:18)
        at serializeInto (...\node_modules\bson\lib\bson\parser\serializer.js:776:17)
        at serializeObject (...\node_modules\bson\lib\bson\parser\serializer.js:308:18)
        at serializeInto (...\node_modules\bson\lib\bson\parser\serializer.js:618:17)
        at serializeObject (...\node_modules\bson\lib\bson\parser\serializer.js:308:18)
        at serializeInto (...\node_modules\bson\lib\bson\parser\serializer.js:776:17)
        at BSON.serialize (...\node_modules\bson\lib\bson\bson.js:58:27)
        at Query.toBin (...\node_modules\mongodb-core\lib\connection\commands.js:140:25)
        at Pool.write (...\node_modules\mongodb-core\lib\connection\pool.js:973:23)

And this is my gulp file:

    var gulp = require('gulp');
    var mongodbData = require('gulp-mongodb-data');
    
    const DB_URI = 'mongodb://localhost:27017/app_db';
    
    gulp.task('init-database', () => {
        gulp.src('./test-database/*.json')
            .pipe(mongodbData({ mongoUrl: DB_URI, dropCollection: true }));
    });

Am I doing something wrong?

**Comment by benne** [comment]
@kleber-swf I must admit I haven't looked at this package for a long time, due to not having to use it, unfortunately - however, I will try to get it updated, along with probably pulling in your change. Let me just get back to you :)

**Comment by benne** [comment]
Pulled into master. I'll write a test to verify the actual bug, but otherwise it is green across the board.
Again, thanks :)

**Comment by kleber-swf** [comment]
No problem! Great tool, btw.

**Comment by kleber-swf** [comment]
Hi, there!
I don't know if it's just me but the package on npm still has the old code (without this fix).
Is that right?

**Comment by benne** [comment]
Just took a look at it - and as far as I know, your PR was merged into both the 2.1.1 and 3.0.0 release:
https://github.com/benne/gulp-mongodb-data/commits/master

Just to be sure, I downloaded both the 2.1.1 and 3.0.0 release and verified the code - and it seems to be there - so I am not sure if it is because your dependency is pinned at 2.1.0, or something like that.

I checked the packages at:
https://registry.npmjs.org/gulp-mongodb-data/-/gulp-mongodb-data-2.1.1.tgz and 
https://registry.npmjs.org/gulp-mongodb-data/-/gulp-mongodb-data-3.0.0.tgz

Did you manage to get it resolved?

**Comment by kleber-swf** [comment]
Yep. Sorry. It WAS just me hahah.
My version was "^2.1.0". Just updated to "^3.0.0" and it's there!
Sorry for the trouble!

**Comment by benne** [comment]
No problem - I am just happy we got it resolved :)
